
#Section 分组节点
[login]
#栏位
    [[login.login]]
        Rule="Required"
        Message={zh_CN="login参数必填",en_US="login is required"}
    [[login.login]]      
        Rule="MinSize(6)"
        Message={zh_CN="passwd参数长度至少要6位",en_US="passwd should be longer than 6 chars"}

    [[login.passwd]]
        Rule="Required"
        Message={zh_CN="login参数必填",en_US="login is required"}
    [[login.passwd]]    
        Rule="MaxSize(6)"
        Message={zh_CN="passwd参数长度要少于12位",en_US="passwd shouldn't be longer than 6 chars"}
