// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/syncRounting.proto

package pkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncRounting struct {
	// RountingNames
	RountingNames string `protobuf:"bytes,1,opt,name=RountingNames,proto3" json:"RountingNames,omitempty"`
	// Parameters
	Parameters string `protobuf:"bytes,2,opt,name=Parameters,proto3" json:"Parameters,omitempty"`
	// QueryStrings
	QueryStrings         string   `protobuf:"bytes,3,opt,name=QueryStrings,proto3" json:"QueryStrings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRounting) Reset()         { *m = SyncRounting{} }
func (m *SyncRounting) String() string { return proto.CompactTextString(m) }
func (*SyncRounting) ProtoMessage()    {}
func (*SyncRounting) Descriptor() ([]byte, []int) {
	return fileDescriptor_b814a9e5848b8e3c, []int{0}
}

func (m *SyncRounting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRounting.Unmarshal(m, b)
}
func (m *SyncRounting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRounting.Marshal(b, m, deterministic)
}
func (m *SyncRounting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRounting.Merge(m, src)
}
func (m *SyncRounting) XXX_Size() int {
	return xxx_messageInfo_SyncRounting.Size(m)
}
func (m *SyncRounting) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRounting.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRounting proto.InternalMessageInfo

func (m *SyncRounting) GetRountingNames() string {
	if m != nil {
		return m.RountingNames
	}
	return ""
}

func (m *SyncRounting) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

func (m *SyncRounting) GetQueryStrings() string {
	if m != nil {
		return m.QueryStrings
	}
	return ""
}

func init() {
	proto.RegisterType((*SyncRounting)(nil), "pkg.SyncRounting")
}

func init() { proto.RegisterFile("pkg/syncRounting.proto", fileDescriptor_b814a9e5848b8e3c) }

var fileDescriptor_b814a9e5848b8e3c = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xc8, 0x4e, 0xd7,
	0x2f, 0xae, 0xcc, 0x4b, 0x0e, 0xca, 0x2f, 0xcd, 0x2b, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2e, 0xc8, 0x4e, 0x57, 0xaa, 0xe0, 0xe2, 0x09, 0x46, 0x92, 0x12, 0x52,
	0xe1, 0xe2, 0x85, 0xb1, 0xfd, 0x12, 0x73, 0x53, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x50, 0x05, 0x85, 0xe4, 0xb8, 0xb8, 0x02, 0x12, 0x8b, 0x12, 0x73, 0x53, 0x4b, 0x52, 0x8b, 0x8a,
	0x25, 0x98, 0xc0, 0x4a, 0x90, 0x44, 0x84, 0x94, 0xb8, 0x78, 0x02, 0x4b, 0x53, 0x8b, 0x2a, 0x83,
	0x4b, 0x8a, 0x32, 0xf3, 0xd2, 0x8b, 0x25, 0x98, 0xc1, 0x2a, 0x50, 0xc4, 0x92, 0xd8, 0xc0, 0xae,
	0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x46, 0x41, 0x1a, 0x9d, 0x9f, 0x00, 0x00, 0x00,
}
