name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: cfg:Build
      run: cd $GITHUB_WORKSPACE/cfg && go build -v ./...

    - name: cfg:Test
      run: cd $GITHUB_WORKSPACE/cfg && go test -v ./...

    - name: Run coverage
      run: cd $GITHUB_WORKSPACE/cfg && go test -race -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage to Codecov
      run: cd $GITHUB_WORKSPACE/cfg && bash <(curl -s https://codecov.io/bash)
