name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: cfg:testing
      run: cd $GITHUB_WORKSPACE/cfg && go test -race -coverprofile=coverage.txt -covermode=atomic
    
    - name: cfg:Codecov
      run: cd $GITHUB_WORKSPACE/cfg && bash <(curl -s https://codecov.io/bash)

    - name: fmt:testing
      run: cd $GITHUB_WORKSPACE/fmt && go test -race -coverprofile=coverage.txt -covermode=atomic
    
    - name: fmt:Codecov
      run: cd $GITHUB_WORKSPACE/fmt && bash <(curl -s https://codecov.io/bash)
